# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"base_path": "00_leaderboard.ipynb",
         "numpy_evaluate": "02_modelling.ipynb",
         "evaluate_torch": "02_modelling.ipynb",
         "get_Xy": "02_modelling.ipynb",
         "radical_merging": "02_modelling.ipynb",
         "split_dataset": "02_modelling.ipynb"}

modules = ["leaderboard.py",
           "inspection.py",
           "modelling.py"]

doc_url = "https://eschmidt42.github.io/ashrae/"

git_url = "https://github.com/eschmidt42/ashrae/tree/master/"

def custom_doc_links(name): return None
