# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_path": "00_leaderboard.ipynb",
         "get_csvs": "01_inspection.ipynb",
         "CSV_NAMES": "01_inspection.ipynb",
         "get_core_Xy": "01_inspection.ipynb",
         "show_nans": "01_inspection.ipynb",
         "get_building_X": "01_inspection.ipynb",
         "get_weather_X": "01_inspection.ipynb",
         "InspectTimeseries": "01_inspection.ipynb",
         "InspectTimeseries.init_widgets": "01_inspection.ipynb",
         "InspectTimeseries.inspect_boldly": "01_inspection.ipynb",
         "InspectTimeseries.click_boldly": "01_inspection.ipynb",
         "InspectTimeseries.select_boldly_all": "01_inspection.ipynb",
         "InspectTimeseries.select_boldly_random": "01_inspection.ipynb",
         "InspectTimeseries.select_boldly_filled_weeks": "01_inspection.ipynb",
         "InspectTimeseries.select_boldly_outlying": "01_inspection.ipynb",
         "InspectTimeseries.plot_boldly": "01_inspection.ipynb",
         "split_dataset": "02_preprocessing.ipynb",
         "Processor": "02_preprocessing.ipynb",
         "DEP_VAR": "02_preprocessing.ipynb",
         "TIME_COL": "02_preprocessing.ipynb",
         "Processor.fix_bid_363": "02_preprocessing.ipynb",
         "Processor.remove_imputed_weeks": "02_preprocessing.ipynb",
         "Processor.remove_outliers": "02_preprocessing.ipynb",
         "Processor.add_building_features": "02_preprocessing.ipynb",
         "Processor.add_weather_features": "02_preprocessing.ipynb",
         "Processor.add_time_features": "02_preprocessing.ipynb",
         "Processor.add_dep_var_stats": "02_preprocessing.ipynb",
         "DEFAULT_GRP_COLS": "02_preprocessing.ipynb",
         "Processor.add_onehot_encoded": "02_preprocessing.ipynb",
         "DEFAULT_ONEHOT_COLS": "02_preprocessing.ipynb",
         "align_test": "02_preprocessing.ipynb",
         "test_var_names": "02_preprocessing.ipynb",
         "store_var_names": "02_preprocessing.ipynb",
         "load_var_names": "02_preprocessing.ipynb",
         "store_df": "02_preprocessing.ipynb",
         "load_df": "02_preprocessing.ipynb",
         "get_tabular_object": "02_preprocessing.ipynb",
         "train_predict": "02_preprocessing.ipynb",
         "SPLIT_PARAMS": "02_preprocessing.ipynb",
         "hist_plot_preds": "02_preprocessing.ipynb",
         "BoldlyWrongTimeseries": "02_preprocessing.ipynb",
         "BoldlyWrongTimeseries.plot_boldly_wrong": "02_preprocessing.ipynb",
         "BoldlyWrongTimeseries.init_widgets": "02_preprocessing.ipynb",
         "BoldlyWrongTimeseries.run_boldly": "02_preprocessing.ipynb",
         "BoldlyWrongTimeseries.click_boldly_wrong": "02_preprocessing.ipynb",
         "evaluate_torch": "03_modelling.ipynb",
         "cnr": "03_modelling.ipynb",
         "Swish": "03_modelling.ipynb",
         "Sine": "03_modelling.ipynb",
         "pick_random": "03_modelling.ipynb"}

modules = ["leaderboard.py",
           "inspection.py",
           "preprocessing.py",
           "modelling.py"]

doc_url = "https://eschmidt42.github.io/ashrae/"

git_url = "https://github.com/eschmidt42/ashrae/tree/master/"

def custom_doc_links(name): return None
