# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_leaderboard.ipynb (unless otherwise specified).

__all__ = ['data_path']

# Cell
import pandas as pd
from pathlib import Path
import os
import plotly.graph_objects as go
import plotly.express as px
from ashrae import inspection

# Cell
data_path = Path("../data")