# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_leaderboard.ipynb (unless otherwise specified).

__all__ = ['base_path']

# Cell
import pandas as pd
from pathlib import Path
import os
import plotly.graph_objects as go
import plotly.express as px

# Cell
base_path = Path("../data")